spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:15432/board
    username: scott
    password: tiger
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        use_sql_comments: true

  data:
    web:
      pageable:
        default-page-size: 5

logging.level:
  com.personal.board: debug
  org.hibernate.SQL: debug

jwt:
  #  header: Authorization
  secret: c2V1bmdiaW4ta2ltLXNwcmluZy1ib290LWhpZXJhcmNoaWNhbC1ib2FyZC1hcGktc2VydmVyLWp3dC1zZWNyZXQ=
  token-validity-in-seconds: 180