spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/scott
    username: scott
    password: tiger
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        #        show_sql: true
        format_sql: true
        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
