spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/scott
    username: scott
    password: tiger
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        #        show_sql: true
        format_sql: true
        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

jwt:
  header: Authorization
  secret: aGVsbG8sIG15IG5hbWUgaXMgc2V1bmdiaW4ga2ltLgpteSBjZWxsIHBob25lIG51bWJlciBpcyAwMTAtNzQ3OC03Mzg5Lg==
  token-validity-in-seconds: 86400
